name: Test Deploy

on:
  workflow_dispatch:  # Only manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create empty file
        run: touch test.txt
      - name: Deploy to GitHub Pages (Test)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages # Ensure branch name