name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch if needed

  # Allows manual triggering
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # Use npm ci for a clean, consistent install

      - name: Build website
        run: npm run build   # Now we KNOW this is 'tsc && vite build'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist    # Correct, as per the default Vite output
          # Optional, uncomment and customize for custom domain:
          # cname: example.com